//SPECIALITIES
export const CREATE_SPECIALITIE = 'CREATE_SPECIALITIE'
export const ADD_SPECIALITIE = 'ADD_SPECIALITIE'
export const EDIT_SPECIALITIE = 'EDIT_SPECIALITIE'
export const DELETE_SPECIALITIE = 'DELETE_SPECIALITIE'
//GROUPS
export const SET_GROUPS_FOR_UMO = 'SET_GROUPS_FOR_UMO'
export const ADD_GROUP = 'ADD_GROUP'
export const EDIT_GROUP = 'EDIT_GROUP'
export const DELETE_GROUP = 'DELETE_GROUP'
export const ADD_CACHE_GROUP_DATA = 'ADD_CACHE_GROUP_DATA'
export const ADD_ID_CACHE_GROUP_DATA = 'ADD_ID_CACHE_GROUP_DATA'
//PLACE
export const ADD_PLACE = 'ADD_PLACE'
export const EDIT_PLACE = 'EDIT_PLACE'
export const DELETE_PLACE = 'DELETE_PLACE'
//USERPOSTS
export const ADD_USERPOST = 'ADD_USERPOST'
export const EDIT_USERPOST = 'EDIT_USERPOST'
export const DELETE_USERPOST = 'DELETE_USERPOST'
//USERS
export const ADD_USER = 'ADD_USER'
export const EDIT_USER = 'EDIT_USER'
export const DELETE_USER = 'DELETE_USER'
//TIMETABLE
export const EDIT_TIMETABLE = 'EDIT_TIMETABLE'
export const SET_TEACHER_TIMETABLE = 'SET_TEACHER_TIMETABLE'
export const SET_TEACHER_TIMETABLE_FULL = 'SET_TEACHER_TIMETABLE_FULL'
//CALLSCHEDULE
export const EDIT_CALL_SCHEDULE = 'EDIT_CALL_SCHEDULE'
//FEADBACK
export const FILL_UP_FEEDBACK = 'FILL_UP_FEEDBACK'
export const RESPOND = 'RESPOND'
export const EDIT_ANSWERED = 'EDIT_ANSWERED'
//СERTIFICATE
export const SET_СERTIFICATE = 'SET_СERTIFICATE'
export const ADD_СERTIFICATE = 'ADD_СERTIFICATE'
export const RESPOND_СERTIFICATE = 'RESPOND_СERTIFICATE'
export const CANCEL_СERTIFICATE = 'CANCEL_СERTIFICATE'
//NOTIFICATIONS
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const EDIT_NOTIFICATIONS = 'EDIT_NOTIFICATIONS'
export const EDIT_ALL_NOTIFICATIONS = 'EDIT_ALL_NOTIFICATIONS'
//CLASSROOM FOUNDATION
export const SET_CLASSROOM_FOUNDATION = 'SET_CLASSROOM_FOUNDATION'
export const SET_ONE_TEACHER_CLASSROOM_FOUNDATION = 'SET_ONE_TEACHER_CLASSROOM_FOUNDATION'
export const EDIT_CLASSROOM_FOUNDATION = 'EDIT_CLASSROOM_FOUNDATION'
export const CLEAR_ONE_TEACHER_CLASSROOM_FOUNDATION = 'CLEAR_ONE_TEACHER_CLASSROOM_FOUNDATION'
export const SEND_CLASSROOM_FOUNDATION = 'SEND_CLASSROOM_FOUNDATION'
//JOURNALS
export const SET_JOURNALS_GROUPS = 'SET_JOURNALS_GROUPS'
export const SET_GROUPS_SUBJECTS = 'SET_GROUPS_SUBJECTS'
export const ADD_CACHE_GROUPS_SUBJECTS = 'ADD_CACHE_GROUPS_SUBJECTS'
export const SET_GROUP_TO_LABEL = 'SET_GROUP_TO_LABEL'
