//SPECIALITIES
export const CREATE_SPECIALITIE = 'CREATE_SPECIALITIE'
export const ADD_SPECIALITIE = 'ADD_SPECIALITIE'
export const EDIT_SPECIALITIE = 'EDIT_SPECIALITIE'
export const DELETE_SPECIALITIE = 'DELETE_SPECIALITIE'
//GROUPS
export const ADD_GROUP = 'ADD_GROUP'
export const EDIT_GROUP = 'EDIT_GROUP'
export const DELETE_GROUP = 'DELETE_GROUP'
export const ADD_CACHE_GROUP_DATA = 'ADD_CACHE_GROUP_DATA'
export const ADD_ID_CACHE_GROUP_DATA = 'ADD_ID_CACHE_GROUP_DATA'
//PLACE
export const ADD_PLACE = 'ADD_PLACE'
export const EDIT_PLACE = 'EDIT_PLACE'
export const DELETE_PLACE = 'DELETE_PLACE'
//USERPOSTS
export const ADD_USERPOST = 'ADD_USERPOST'
export const EDIT_USERPOST = 'EDIT_USERPOST'
export const DELETE_USERPOST = 'DELETE_USERPOST'
//USERS
export const ADD_USER = 'ADD_USER'
export const EDIT_USER = 'EDIT_USER'
export const DELETE_USER = 'DELETE_USER'
//TIMETABLE
export const EDIT_TIMETABLE = 'EDIT_TIMETABLE'
//CALLSCHEDULE
export const EDIT_CALL_SCHEDULE = 'EDIT_CALL_SCHEDULE'
//FEADBACK
export const FILL_UP_FEEDBACK = 'FILL_UP_FEEDBACK'
export const RESPOND = 'RESPOND'
