// SNACKBAR
export const SET_SNACKBAR_SHOW = 'SET_SNACKBAR_SHOW'
export const SET_SNACKBAR_COLOR = 'SET_SNACKBAR_COLOR'
export const SET_SNACKBAR_TEXT = 'SET_SNACKBAR_TEXT'
export const SET_SNACKBAR_SUBTEXT = 'SET_SNACKBAR_SUBTEXT'
export const SET_SNACKBAR_TIMEOUT = 'SET_SNACKBAR_TIMEOUT'
// OVERLAYLOADING
export const SET_OVERLAYLOADING_TEXT_DELETE = 'SET_OVERLAYLOADING_TEXT_DELETE'
export const SET_OVERLAYLOADING_TEXT_FULL = 'SET_OVERLAYLOADING_TEXT_FULL'
export const SET_OVERLAYLOADING_TEXT = 'SET_OVERLAYLOADING_TEXT'
export const SET_OVERLAYLOADING_SHOW = 'SET_OVERLAYLOADING_SHOW'
// AUTH
export const SET_AUTH = 'SET_AUTH'
export const SET_NOTAUTH = 'SET_NOTAUTH'
// Server Setting
export const SET_SERVER = 'SET_SERVER'
export const SET_PROFILACTIC = 'SET_PROFILACTIC'
//SPECIALITIES
export const SET_SPECIALITIES_FULL = 'SET_SPECIALITIES_FULL'
export const SET_SPECIALITIES_COMBO = 'SET_SPECIALITIES_COMBO'
//GROUPS
export const SET_GROUPS_FULL = 'SET_GROUPS_FULL'
export const SET_GROUPS_COMBO = 'SET_GROUPS_COMBO'
//PLACES
export const SET_PLACES_FULL = 'SET_PLACES_FULL'
export const SET_PLACES_COMBO = 'SET_PLACES_COMBO'
//USERPOSTS
export const SET_USERPOSTS_FULL = 'SET_USERPOSTS_FULL'
//USERS
export const SET_USERS_FULL = 'SET_USERS_FULL'
//TEACHERS
export const SET_TEACHERS_COMBO = 'SET_TEACHERS_COMBO'
//DISCIPLINES
export const SET_DISCIPLINES_COMBO = 'SET_DISCIPLINES_COMBO'
//TIMETABLE
export const SET_TIMETABLE_FULL = 'SET_TIMETABLE_FULL'
//CALLSCHEDULE
export const SET_CALL_SCHEDULE = 'SET_CALL_SCHEDULE'
//FEADBACK
export const SET_FEEDBACK = 'SET_FEEDBACK'










