// SNACKBAR
export const SET_SNACKBAR_SHOW = 'SET_SNACKBAR_SHOW'
export const SET_SNACKBAR_COLOR = 'SET_SNACKBAR_COLOR'
export const SET_SNACKBAR_TEXT = 'SET_SNACKBAR_TEXT'
export const SET_SNACKBAR_SUBTEXT = 'SET_SNACKBAR_SUBTEXT'
export const SET_SNACKBAR_TIMEOUT = 'SET_SNACKBAR_TIMEOUT'
// OVERLAYLOADING
export const SET_OVERLAYLOADING_SHOW = 'SET_OVERLAYLOADING_SHOW'
export const SET_OVERLAYLOADING_TEXT = 'SET_OVERLAYLOADING_TEXT'

export const SET_AUTH = 'SET_AUTH'
export const SET_NOTAUTH = 'SET_NOTAUTH'

export const SET_SERVER = 'SET_SERVER'






